# AgriChain Channel Configuration
Organizations:
  - 
      Name: OrdererOrg
      ID: OrdererMSP
      MSPDir: ./orderer/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('OrdererMSP.member')"
        Writers:
          Type: Signature
          Rule: "OR('OrdererMSP.member')"
        Admins:
          Type: Signature
          Rule: "OR('OrdererMSP.admin')"
      OrdererEndpoints:
        - orderer.agrichain.com:7050

  - 
      Name: Org1MSP
      ID: Org1MSP
      MSPDir: ./org1/peer0/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
        Writers:
          Type: Signature
          Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
        Admins:
          Type: Signature
          Rule: "OR('Org1MSP.admin')"
        Endorsement:
          Type: Signature
          Rule: "OR('Org1MSP.peer')"
      AnchorPeers:
        - Host: peer0.org1.agrichain.com
          Port: 7051

  - 
      Name: Org2MSP
      ID: Org2MSP
      MSPDir: ./org2/peer0/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')"
        Writers:
          Type: Signature
          Rule: "OR('Org2MSP.admin', 'Org2MSP.client')"
        Admins:
          Type: Signature
          Rule: "OR('Org2MSP.admin')"
        Endorsement:
          Type: Signature
          Rule: "OR('Org2MSP.peer')"
      AnchorPeers:
        - Host: peer0.org2.agrichain.com
          Port: 9051

Capabilities:
  Channel: 
    V2_0: true
  Orderer: 
    V2_0: true
  Application: 
    V2_0: true

Application: 
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Profiles:
  AgriChainChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org1
        - *Org2
      Capabilities:
        <<: *ApplicationCapabilities
